{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-monitor.serviceAccountName" . }}
  namespace:  {{ .Values.namespace.name }}
  labels:
    {{- include "node-monitor.labels" . | nindent 4 }}
{{- end }}
