# Default values for node-monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "quay.io/support-tools/monitor-tools:latest"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

serviceAccount:
  create: true
  name: "node-metrics-sa"

nodeSelector: 
  collect-node-metrics: ""  

tolerations: 
- key: node-role.kubernetes.io/master
  effect: NoSchedule

namespace:
  name: "node-metrics"
  
affinity: {}   
      